

services:

  desktop_app:
    build:
      context: ./desktop_app
      dockerfile: dockerfile
    container_name: desktop_app_container
    ports:
      - "8080:8080" # Adjust the port mapping as needed
    volumes:
      - ./desktop_app:/app
    environment:
      - ENV=production # Add any required environment variables

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins_container
    ports:
      - "8081:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false # Skip setup wizard if needed

volumes:
  jenkins_home: